services:
  api:
    build:
      context: .
      dockerfile: ProfDropFunctions/Dockerfile
    ports:
      - "7293:80"
    environment:
      FUNCTIONS_WORKER_RUNTIME: dotnet-isolated
      AzureWebJobsStorage: ${AZURE_STORAGE_CONNECTION_STRING}
      AzureWebJobsSecretStorageType: files
      FUNCTIONS_SECRETS_PATH: /azure-functions-host/Secrets
    volumes:
      - ./function-secrets:/azure-functions-host/Secrets

  web:
    build:
      context: .
      dockerfile: ProfDropMVC/Dockerfile
    ports:
      - "7216:8080"
    environment:
      ASPNETCORE_URLS: http://+:8080
      ProfDropApi__BaseUrl: http://api/api/
      ProfDropApi__FunctionKey: ${PROFDROP_FUNCTION_KEY}
    depends_on:
      - api